apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
  labels:
    app: simple-web-app
spec:
  type: NodePort
  selector:
    app: simple-web-app
  ports:
    - protocol: TCP
      port: 5000       # The internal port the app listens on
      targetPort: 5000  # The port in the container
      nodePort: 30007   # The external port for accessing the app (optional)
